# https://taskfile.dev

version: "3"

tasks:
  default:
    cmd: task test

  lint:
    desc: Run linter for Go
    cmd: golangci-lint run ./...

  test:
    desc: Run tests for Go
    cmd: go test -v ./...
